[tools]
"cargo:cargo-deb" = "3.7.0"
"aqua:nextest-rs/nextest/cargo-nextest" = "0.9.140"
"cargo:cargo-zigbuild" = "0.23.2"
zig = "0.16.0"

[settings]
idiomatic_version_file_enable_tools = ["rust"]
lockfile = true

[tasks.ci]
run = "cargo check --all-targets --all-features --locked"

[tasks.test]
run = "cargo nextest run --all-features --color=always --no-tests=pass"

[tasks.lint]
run = "cargo clippy --all-targets -- -D warnings"

[tasks.fmt]
run = "cargo fmt --all --check"
