use std::{
    collections::HashSet,
    path::{Path, PathBuf},
    time::{Duration, SystemTime},
};

mod artifacts;
mod sizing;

pub use artifacts::{Artifact, classify_artifact, collect_artifacts, default_project_roots};
pub use sizing::{Candidate, SizeEvent, SizeHandle, size};

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Safety {
    Rebuildable,
    CacheOldOnly,
    ReviewFirst,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RootPattern {
    Home(&'static str),
    XdgCache(&'static str),
    PnpmStore,
    Special,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Detect {
    Always,
    ToolOnPath(&'static str),
    DirExists,
    ToolOrDir(&'static str),
}

#[derive(Debug)]
pub struct InsightSpec {
    pub id: &'static str,
    pub title: &'static str,
    pub explain: &'static str,
    pub safety: Safety,
    pub roots: &'static [RootPattern],
    pub min_age_days: Option<u32>,
    pub detect: Detect,
    pub skip_if_running: Option<&'static str>,
}

#[derive(Debug, Clone)]
pub struct Probe {
    pub home: PathBuf,
    pub xdg_cache_home: Option<PathBuf>,
    pub tools: HashSet<String>,
    pub existing_dirs: HashSet<PathBuf>,
}

impl Probe {
    pub fn current() -> Option<Self> {
        let home = dirs::home_dir()?;
        let xdg_cache_home = std::env::var_os("XDG_CACHE_HOME")
            .filter(|value| !value.is_empty())
            .map(PathBuf::from);
        let tools = TOOL_NAMES
            .iter()
            .filter(|tool| which::which(tool).is_ok())
            .map(|tool| (*tool).to_owned())
            .collect();
        let mut probe = Self {
            home,
            xdg_cache_home,
            tools,
            existing_dirs: HashSet::new(),
        };
        for spec in REGISTRY {
            probe.existing_dirs.extend(
                expand_roots_with_xdg(spec, &probe.home, probe.xdg_cache_home.as_deref())
                    .into_iter()
                    .filter(|path| path.is_dir()),
            );
        }
        Some(probe)
    }
}

const TOOL_NAMES: &[&str] = &[
    "brew", "npm", "pnpm", "yarn", "bun", "cargo", "pip3", "uv", "docker",
];

const XCODE_DERIVED: &[RootPattern] = &[RootPattern::Home("Library/Developer/Xcode/DerivedData")];
const XCODE_DEVICE: &[RootPattern] = &[
    RootPattern::Home("Library/Developer/Xcode/iOS DeviceSupport"),
    RootPattern::Home("Library/Developer/Xcode/watchOS DeviceSupport"),
    RootPattern::Home("Library/Developer/Xcode/tvOS DeviceSupport"),
];
const XCODE_ARCHIVES: &[RootPattern] = &[RootPattern::Home("Library/Developer/Xcode/Archives")];
const SIMULATOR: &[RootPattern] = &[RootPattern::Home("Library/Developer/CoreSimulator/Caches")];
const BREW: &[RootPattern] = &[RootPattern::Home("Library/Caches/Homebrew")];
const NPM: &[RootPattern] = &[
    RootPattern::Home(".npm/_cacache"),
    RootPattern::Home(".npm/_logs"),
];
const PNPM: &[RootPattern] = &[RootPattern::PnpmStore];
const YARN: &[RootPattern] = &[
    RootPattern::Home(".yarn/cache"),
    RootPattern::Home("Library/Caches/Yarn"),
];
const BUN: &[RootPattern] = &[RootPattern::Home(".bun/install/cache")];
const CARGO: &[RootPattern] = &[
    RootPattern::Home(".cargo/registry/cache"),
    RootPattern::Home(".cargo/git"),
];
const GRADLE: &[RootPattern] = &[
    RootPattern::Home(".gradle/caches"),
    RootPattern::Home(".gradle/daemon"),
    RootPattern::Home(".gradle/wrapper/dists"),
];
const MAVEN: &[RootPattern] = &[RootPattern::Home(".m2/repository")];
const PIP: &[RootPattern] = &[RootPattern::Home("Library/Caches/pip")];
const UV: &[RootPattern] = &[RootPattern::XdgCache("uv")];
const USER_CACHES: &[RootPattern] = &[RootPattern::Home("Library/Caches")];
const USER_LOGS: &[RootPattern] = &[RootPattern::Home("Library/Logs")];
const JETBRAINS_LOGS: &[RootPattern] = &[RootPattern::Home("Library/Logs/JetBrains")];
const SPECIAL: &[RootPattern] = &[RootPattern::Special];

pub const REGISTRY: &[InsightSpec] = &[
    InsightSpec {
        id: "xcode.derived-data",
        title: "Xcode DerivedData",
        explain: "Build indexes and products regenerated by Xcode on demand.",
        safety: Safety::Rebuildable,
        roots: XCODE_DERIVED,
        min_age_days: None,
        detect: Detect::DirExists,
        skip_if_running: Some("Xcode"),
    },
    InsightSpec {
        id: "xcode.device-support",
        title: "Xcode device support",
        explain: "Symbols and support files reacquired when an older device reconnects.",
        safety: Safety::CacheOldOnly,
        roots: XCODE_DEVICE,
        min_age_days: Some(90),
        detect: Detect::DirExists,
        skip_if_running: None,
    },
    InsightSpec {
        id: "xcode.archives",
        title: "Xcode archives",
        explain: "Signed build archives may be needed for symbolication or redistribution.",
        safety: Safety::ReviewFirst,
        roots: XCODE_ARCHIVES,
        min_age_days: None,
        detect: Detect::DirExists,
        skip_if_running: None,
    },
    InsightSpec {
        id: "simulator.caches",
        title: "Simulator caches",
        explain: "Simulator cache data rebuilt as simulators run.",
        safety: Safety::Rebuildable,
        roots: SIMULATOR,
        min_age_days: None,
        detect: Detect::DirExists,
        skip_if_running: Some("Simulator"),
    },
    InsightSpec {
        id: "brew.cache",
        title: "Homebrew cache",
        explain: "Downloaded package archives that Homebrew can fetch again.",
        safety: Safety::Rebuildable,
        roots: BREW,
        min_age_days: None,
        detect: Detect::ToolOnPath("brew"),
        skip_if_running: None,
    },
    InsightSpec {
        id: "npm.cache",
        title: "npm cache and logs",
        explain: "Package cache and logs regenerated by npm.",
        safety: Safety::Rebuildable,
        roots: NPM,
        min_age_days: None,
        detect: Detect::ToolOnPath("npm"),
        skip_if_running: None,
    },
    InsightSpec {
        id: "pnpm.store",
        title: "pnpm store",
        explain: "Old package content that pnpm can download again.",
        safety: Safety::CacheOldOnly,
        roots: PNPM,
        min_age_days: Some(30),
        detect: Detect::ToolOnPath("pnpm"),
        skip_if_running: None,
    },
    InsightSpec {
        id: "yarn.cache",
        title: "Yarn cache",
        explain: "Package archives that Yarn can download again.",
        safety: Safety::Rebuildable,
        roots: YARN,
        min_age_days: None,
        detect: Detect::ToolOnPath("yarn"),
        skip_if_running: None,
    },
    InsightSpec {
        id: "bun.cache",
        title: "Bun cache",
        explain: "Cached packages regenerated by Bun installs.",
        safety: Safety::Rebuildable,
        roots: BUN,
        min_age_days: None,
        detect: Detect::ToolOnPath("bun"),
        skip_if_running: None,
    },
    InsightSpec {
        id: "cargo.registry-cache",
        title: "Cargo registry and Git cache",
        explain: "Old Rust dependency sources that Cargo can fetch again.",
        safety: Safety::CacheOldOnly,
        roots: CARGO,
        min_age_days: Some(30),
        detect: Detect::ToolOnPath("cargo"),
        skip_if_running: None,
    },
    InsightSpec {
        id: "gradle.caches",
        title: "Gradle caches",
        explain: "Old Gradle artifacts and distributions downloaded or rebuilt as needed.",
        safety: Safety::CacheOldOnly,
        roots: GRADLE,
        min_age_days: Some(30),
        detect: Detect::DirExists,
        skip_if_running: None,
    },
    InsightSpec {
        id: "maven.repository",
        title: "Maven repository",
        explain: "Local dependency repository; review snapshots and offline needs first.",
        safety: Safety::ReviewFirst,
        roots: MAVEN,
        min_age_days: None,
        detect: Detect::DirExists,
        skip_if_running: None,
    },
    InsightSpec {
        id: "pip.cache",
        title: "pip cache",
        explain: "Python package downloads and wheels that pip can fetch or rebuild.",
        safety: Safety::Rebuildable,
        roots: PIP,
        min_age_days: None,
        detect: Detect::ToolOrDir("pip3"),
        skip_if_running: None,
    },
    InsightSpec {
        id: "uv.cache",
        title: "uv cache",
        explain: "Python package artifacts that uv can fetch or rebuild.",
        safety: Safety::Rebuildable,
        roots: UV,
        min_age_days: None,
        detect: Detect::ToolOnPath("uv"),
        skip_if_running: None,
    },
    InsightSpec {
        id: "docker.data",
        title: "Docker data",
        explain: "Docker-managed images and build cache; review Docker's own accounting first.",
        safety: Safety::ReviewFirst,
        roots: SPECIAL,
        min_age_days: None,
        detect: Detect::ToolOnPath("docker"),
        skip_if_running: None,
    },
    InsightSpec {
        id: "user.caches",
        title: "User caches",
        explain: "Per-application caches; review each application entry before cleanup.",
        safety: Safety::ReviewFirst,
        roots: USER_CACHES,
        min_age_days: Some(30),
        detect: Detect::Always,
        skip_if_running: None,
    },
    InsightSpec {
        id: "user.logs",
        title: "User logs",
        explain: "Old diagnostic logs no longer needed by running applications.",
        safety: Safety::Rebuildable,
        roots: USER_LOGS,
        min_age_days: Some(7),
        detect: Detect::Always,
        skip_if_running: None,
    },
    InsightSpec {
        id: "ide.jetbrains-logs",
        title: "JetBrains logs",
        explain: "Old IDE diagnostic logs regenerated during later sessions.",
        safety: Safety::Rebuildable,
        roots: JETBRAINS_LOGS,
        min_age_days: Some(7),
        detect: Detect::DirExists,
        skip_if_running: None,
    },
    InsightSpec {
        id: "project.artifacts",
        title: "Project build artifacts",
        explain: "Generated dependency and build directories; review projects before cleanup.",
        safety: Safety::ReviewFirst,
        roots: SPECIAL,
        min_age_days: Some(7),
        detect: Detect::Always,
        skip_if_running: None,
    },
];

pub fn detect(spec: &InsightSpec, probe: &Probe) -> bool {
    match spec.detect {
        Detect::Always => true,
        Detect::ToolOnPath(tool) => probe.tools.contains(tool),
        Detect::DirExists => {
            expand_roots_with_xdg(spec, &probe.home, probe.xdg_cache_home.as_deref())
                .iter()
                .any(|path| probe.existing_dirs.contains(path))
        }
        Detect::ToolOrDir(tool) => {
            probe.tools.contains(tool)
                || expand_roots_with_xdg(spec, &probe.home, probe.xdg_cache_home.as_deref())
                    .iter()
                    .any(|path| probe.existing_dirs.contains(path))
        }
    }
}

pub fn expand_roots(spec: &InsightSpec, home: &Path) -> Vec<PathBuf> {
    expand_roots_with_xdg(spec, home, None)
}

pub fn expand_roots_with_xdg(
    spec: &InsightSpec,
    home: &Path,
    xdg_cache_home: Option<&Path>,
) -> Vec<PathBuf> {
    spec.roots
        .iter()
        .filter_map(|root| match root {
            RootPattern::Home(relative) => Some(home.join(relative)),
            RootPattern::XdgCache(relative) => Some(
                xdg_cache_home
                    .map_or_else(|| home.join(".cache"), Path::to_path_buf)
                    .join(relative),
            ),
            RootPattern::PnpmStore => Some(home.join("Library/pnpm/store")),
            RootPattern::Special => None,
        })
        .collect()
}

pub fn is_old_enough(mtime: SystemTime, min_age_days: Option<u32>, now: SystemTime) -> bool {
    let Some(days) = min_age_days else {
        return true;
    };
    now.duration_since(mtime).unwrap_or(Duration::ZERO)
        >= Duration::from_secs(u64::from(days) * 24 * 60 * 60)
}

pub fn spec(id: &str) -> Option<&'static InsightSpec> {
    REGISTRY.iter().find(|entry| entry.id == id)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::cleanup::validate;

    fn fake_probe() -> Probe {
        Probe {
            home: "/tmp/fake-home".into(),
            xdg_cache_home: None,
            tools: HashSet::new(),
            existing_dirs: HashSet::new(),
        }
    }

    #[test]
    fn registry_ids_are_unique_and_explanations_nonempty() {
        let mut ids = HashSet::new();
        assert!(REGISTRY.iter().all(|entry| ids.insert(entry.id)));
        assert!(
            REGISTRY
                .iter()
                .all(|entry| !entry.explain.trim().is_empty())
        );
    }

    #[test]
    fn concrete_roots_expand_below_injected_home() {
        let home = Path::new("/tmp/fake-home");
        for entry in REGISTRY {
            for root in expand_roots(entry, home) {
                assert!(root.starts_with(home), "{}: {}", entry.id, root.display());
            }
        }
    }

    #[test]
    fn xdg_cache_override_is_honored() {
        let uv = spec("uv.cache").unwrap();
        assert_eq!(
            expand_roots_with_xdg(uv, Path::new("/home/me"), Some(Path::new("/cache"))),
            [PathBuf::from("/cache/uv")]
        );
    }

    #[test]
    fn detection_uses_injected_tool_and_directory_facts() {
        let mut probe = fake_probe();
        assert!(!detect(spec("brew.cache").unwrap(), &probe));
        probe.tools.insert("brew".into());
        assert!(detect(spec("brew.cache").unwrap(), &probe));
        let derived = expand_roots(spec("xcode.derived-data").unwrap(), &probe.home).remove(0);
        probe.existing_dirs.insert(derived);
        assert!(detect(spec("xcode.derived-data").unwrap(), &probe));
    }

    #[test]
    fn age_gate_treats_future_mtime_as_recent() {
        let now = SystemTime::UNIX_EPOCH + Duration::from_secs(100 * 86_400);
        assert!(is_old_enough(
            now - Duration::from_secs(31 * 86_400),
            Some(30),
            now
        ));
        assert!(!is_old_enough(
            now - Duration::from_secs(29 * 86_400),
            Some(30),
            now
        ));
        assert!(!is_old_enough(now + Duration::from_secs(1), Some(30), now));
        assert!(is_old_enough(now, None, now));
    }

    #[test]
    fn never_touch_user_paths_are_rejected() {
        let Some(home) = dirs::home_dir() else { return };
        for relative in [
            ".Trash/item",
            "Library/Mobile Documents/com~apple~CloudDocs/file",
            "Library/Mobile Documents.old/file",
            "Library/Keychains/login.keychain-db",
            "Library/Application Support/Google/Chrome/Profile 1",
            "Library/Safari/History.db",
            "Library/Containers/com.docker.docker/Data/vms/0/data/Docker.raw",
        ] {
            let path = home.join(relative);
            assert!(validate(&path).is_err(), "{}", path.display());
        }
    }
}
